// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llfeogeglhxbddilmdnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsZmVvZ2VnbGh4YmRkaWxtZG5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzI4MzIsImV4cCI6MjA2Mzg0ODgzMn0.GXj5YKOdC5Isx1A1J4B8b_sa45iVVJGq9640GuQmNDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);